#include<iostream>
using namespace std;

int main(){
	
//Task # 1 Write a program in C++ to compute the total and average of four numbers.
// (take values of four numbers from the user at runtime)  
//Expected output
//Input 1st two numbers (separated by space) : 25 20
//Input last two numbers (separated by space) : 15 25
//The total of four numbers is : 85
//The average of four numbers is : 21.25

//float a,b,c,d;
//cout<<"Enter first two numbers : ";
//cin>>a>>b;
//cout<<"Enter last two numbers : ";
//cin>>c>>d;
//float sum=a+b+c+d;
//cout<<"The total of four numbers is : "<<sum<<endl;
//float average=sum/4;       // as there are four numbers so according to  formula of average
//cout<<"The average of four numbers is : "<<average;

//************************************//

//Task # 2 In the following C++ program , change the C++ single line-style comments to
// C++ multiple line-style comments:

  /* cout<<"Welcome \n!";
  cout<<"Programming  \n!";
  cout<<"Fundamentals \n!";
  cout<<"in C++ \n!";
   cout<<"End of Program";
    */
    
    //************************************//

//Task # 3 Consider the C++ program in Task# 2, remove comments, 
//replace escape sequence \n with endl manipulator and display the output on separate lines.

//  cout<<"Welcome"<<endl<<"!";
//  cout<<"Programming"<<endl<<"!";
//  cout<<"Fundamentals"<<endl<<"!";
//  cout<<"in C++ "<<endl<<"!";
//   cout<<"End of Program";
    
 //************************************//


//Task # 4 Write the #include statement for the standard C++ streams for input/output.

//#include<iostream>

//************************************//

//Task # 5 Write three C++ statements using cout, <<, and endl: 
//
//(a)	one that defines three variables length, width, and area on one line.
//
//(b) another that takes values for length and width variables from the user at runtime 
//(c) another that calculates and outputs the area. (Area=length * width)

//int length , width ,area;     // (a)
//cout<<"Enter length  : "<<endl;     //(b)
//cin>>length;
//cout<<"Enter width  : "<<endl;
//cin>>width;
//area=length*width;
//cout<<"The area is : "<<area<<endl;;     //(c)

//************************************//

return 0;
}
